### ISSUE TITLE
This starter template is out of date

### ISSUE THREAD

**Issue by Scott-Fischer** [clerkinc/remix-bossa-nova-stack#2]
Just to save anyone else the time and trouble, this starter template is really out of date from both the Clerk perspective. The installed version of Clerk in this stack is 2 major version behind the latest release.

**Comment by segheysens** [comment]
It's only a minor version behind, this template is very useful. @perkinsjr I recommend closing this issue (@Scott-Fischer unless you have any additional context and suggestions to share).

**Comment by Scott-Fischer** [comment]
@segheysens You're right, they updated it in [this commit](https://github.com/clerkinc/remix-bossa-nova-stack/commit/26c420feaaa6ec267f64027bf3f6e35659f51e4a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R26) semi-recently. (presumably to fix the same issues that I had run into when I opened this issue in Feb. 2023)

I'll go ahead and close this now.
